import type { ProductRow } from '@/lib/products-map';
import type { ProductInput } from './actions';

export const EMPTY_PRODUCT: ProductInput = {
  name: '',
  price: 0,
  original_price: null,
  image: '',
  images: [],
  videos: [],
  variants: [],
  category: '',
  collections: [],
  brand: null,
  sku: null,
  stock: 0,
  reorder_level: 5,
  cost_price: null,
  hsn: null,
  gst_rate: null,
  tags: [],
  colors: [],
  sizes: [],
  description: '',
  details_care: [],
  shipping_returns: null,
  trending: false,
  new_arrival: false,
  is_active: true,
  sort_order: 0,
};

export function rowToInput(r: ProductRow): ProductInput {
  return {
    name: r.name,
    price: Number(r.price),
    original_price: r.original_price != null ? Number(r.original_price) : null,
    image: r.image,
    images: r.images ?? [],
    videos: r.videos ?? [],
    variants: r.variants ?? [],
    category: r.category,
    collections: r.collections ?? [],
    brand: r.brand ?? null,
    sku: r.sku ?? null,
    stock: r.stock ?? 0,
    reorder_level: r.reorder_level ?? 5,
    cost_price: r.cost_price != null ? Number(r.cost_price) : null,
    hsn: r.hsn ?? null,
    gst_rate: r.gst_rate != null ? Number(r.gst_rate) : null,
    tags: r.tags ?? [],
    colors: r.colors ?? [],
    sizes: r.sizes ?? [],
    description: r.description ?? '',
    details_care: r.details_care ?? [],
    shipping_returns: r.shipping_returns ?? null,
    trending: !!r.trending,
    new_arrival: !!r.new_arrival,
    is_active: r.is_active ?? true,
    sort_order: r.sort_order ?? 0,
  };
}
